# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


# 注：如果没有下载SDK，请直接执行后面代码：  sh init.sh

def pod_beauty(type) 
  pod "TXLiteAVSDK_#{type}"
end

target 'TUIBeautyApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'TXAppBasic', :path => "./TXAppBasic/"
  pod 'TUICore', :path => "../../TUICore/"
  pod 'TUIBeauty', :path => "../"
  pod 'Toast-Swift'
  pod 'Alamofire'
  pod 'Kingfisher'
  pod 'SnapKit'
  pod_beauty('Professional')
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
      config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
      config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
    end
  end
end
