export enum MetricsKey {
  T_METRICS_STATE_API_SET_WIDGET_VISIBLE_COUNT = 192901,
  T_METRICS_STATE_API_REGISTER_WIDGET_COUNT = 192902,
  T_METRICS_STATE_API_ON_WILL_COUNT = 192903,
  T_METRICS_STATE_API_SET_FEATURE_CONFIG_COUNT = 192904,
}
