export enum MetricsKey {
  T_METRICS_STATE_API_SET_WIDGET_VISIBLE_COUNT = 182000,
  T_METRICS_STATE_API_REGISTER_WIDGET_COUNT = 182001,
  T_METRICS_STATE_API_ON_WILL_COUNT = 182002,
  T_METRICS_STATE_API_SET_FEATURE_CONFIG_COUNT = 182003,
}
