import 'dart:ui';

class RoomColors {
  static const Color textWhite = Color(0xFFD5E0F2);
  static const Color btnTextWhite = Color(0xFFD1D9EC);
  static const Color btnBackgroundBlue = Color(0xFF006EFF);
  static const Color mainBlack = Color(0xFF17181F);
  static const Color lightBlack = Color(0xFF1B1E26);
  static const Color darkBlack = Color(0xFF0F1014);
  static const Color lightGrey = Color(0xFF2A2D38);
  static const Color hintGrey = Color(0xFF8F9AB2);
  static const Color btnGrey = Color(0xFF4F586B);
  static const Color btnLightGrey = Color(0x4D4f586B);
  static const Color btnRed = Color(0xFFED414D);
  static const Color translucentLightBlack = Color(0x88121723);
  static const Color fluorescentGreen = Color(0xFFA5FE33);
  static const Color grey = Color(0xff888888);
  static const Color dividerGrey = Color(0x4C4F586B);
  static const Color btnTextGrey = Color(0xFFB2BBD1);
  static const Color btnTextRed = Color(0xFFF2504B);
  static const Color btnBlue = Color(0xFF4791FF);
  static const Color tipGrey = Color(0xFF7C85A6);
  static const Color textRed = Color(0xFFE5395C);
  static const Color toastBlack = Color(0xCC000000);
  static const Color screenBtnTextRed = Color(0xFFCC3D47);
  static const Color textOrange = Color(0xFFF06C4B);
  static const Color dividerLightGrey = Color(0xFFE7ECF6);
  static const Color textHintGrey = Color(0xFFADB6CC);
  static const Color chosenGrey = Color(0xFF4F515A);
  static const Color backgroundGrey = Color(0xFFF8F9FB);
  static const Color titleBlack = Color(0xFF2B2E38);
  static const Color infoBlack = Color(0xB22B2E38);
  static const Color switchTrackGrey = Color(0xFFC5CCDB);
  static const Color menuButtonBlue = Color(0xFF1C66E5);
  static const Color textBlack = Color(0xFF22262E);
  static const Color dividerWhite = Color(0xFFF2F5FC);
  static const Color searchBarGrey = Color(0xFFF4F5F9);
  static const Color titleTimeGrey = Color(0xFF969EB4);
  static const Color newLightGrey = Color(0xFFF0F3FA);
  static const Color btnTextBlack = Color(0xFF4E5461);
  static const Color btnTextBlue = Color(0xFF0961F7);
  static const Color lightPink = Color(0xFFFAF0F0);
}
