use_frameworks!

platform :ios, '13.0'

# UI库
def ui
  pod 'SnapKit'
end

# 工具库
def tool
  pod 'Alamofire'
  pod 'TUICore'
  pod 'TUIChat'
  pod 'TUIRoomEngine','1.5.0'
  pod 'TXLiteAVSDK_TRTC'
  pod 'TXAppBasic'
  pod 'TIMCommon'
  pod 'TXIMSDK_Plus_iOS'
end

# 本地依赖库
def local
  pod 'TUIRoomKit', :path => "../TUIRoomKit/"
end


target 'DemoApp' do
  ui
  tool
  local
  
  # 屏幕分享扩展Podfile配置
  target 'TXReplayKit_Screen' do
    inherit! :search_paths
    pod 'TXLiteAVSDK_TRTC/ReplayKitExt'
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = 13.0
      if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
        target.build_configurations.each do |config|
            config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
    end
  end
end
