use_frameworks!

platform :ios, '12.0'
source 'https://github.com/CocoaPods/Specs.git'

# UI库
def ui
  pod 'SnapKit'
end

# 工具库
def tool
  pod 'Alamofire'
  pod 'TUICore'
  pod 'TUIRoomEngine', '1.0.1'
  pod 'TXLiteAVSDK_TRTC'
  pod 'TXAppBasic'
end

# 本地依赖库
def local
  pod 'TUIRoomKit', :path => '../TUIRoomKit/'
  pod 'TUIVideoSeat', :path => '../TUIVideoSeat/'
  pod 'TUIBeauty',  :path => "../TUIBeauty"
end


target 'DemoApp' do
  ui
  tool
  local
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = 13.0
      if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
        target.build_configurations.each do |config|
            config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
    end
  end
end
